### ISSUE TITLE
[style] improve dashboard UI/UX

### ISSUE THREAD

**Issue by 21ow** [najitwo/10-Sprint-Taskify#120]
## 📝 Description

- 대시보드 디자인 개선

## ✅ To-Dos

- [x] 헤더, 푸터 고정
- [x] 드래그, 드롭 시각적 스타일 추가
- [ ] 스크롤, 드롭 영역 개선
- [x] 태블릿 뷰: 컬럼 추가 버튼 찌그러짐
