### ISSUE TITLE
[feat] add mypage layout and finalize styling

### ISSUE THREAD

**Issue by najitwo** [najitwo/10-Sprint-Taskify#15]
## 📝 Description

- 마이페이지 레이아웃 완성 및 CSS 마무리

## ✅ To-Dos

- [x] 마이페이지 레이아웃 추가
- [x] CSS 스타일 작업 마무리
- [x] alert 모달 추가
