### ISSUE TITLE
[refactor] split components into separate files

### ISSUE THREAD

**Issue by 21ow** [najitwo/10-Sprint-Taskify#48]
## 📝 Description

- 대시보드 상세 페이지 코드 분리

## ✅ To-Dos

- [x] 컬럼 컴포 분리
- [x] 카드 컴포 분리
- [x] DnD 로직 분리
