### ISSUE TITLE
[feat] add header, sidebar content

### ISSUE THREAD

**Issue by devmanta** [najitwo/10-Sprint-Taskify#5]
## 📝 Description

- 헤더, 사이드바 내용 추가

## ✅ To-Dos

- [x] 헤더 내정보 표시
- [x] 헤더 관리, 초대하기 버튼 추가
- [x] API호출 함수 추가
