### ISSUE TITLE
[feat] integrate user API for mypage

### ISSUE THREAD

**Issue by najitwo** [najitwo/10-Sprint-Taskify#7]
## 📝 Description

- 마이페이지 유저 API 연동

## ✅ To-Dos

- [x] API 호출 함수 만들기
- [x] 사용자 정보 가져오기
- [x] 사용자 정보 수정하기
